### PR TITLE
[FIX] Fix to use big values on selector. Issue: https://github.com/mi…

### PR DESCRIPTION
**Pull request by mathias21**
…losmns/actual-number-picker/issues/8. Tested with values: (app:max_value="4016" app:min_value="1008" app:value="2016" // app:max_value="16" app:min_value="1" app:value="5" // app:max_value="200" app:min_value="19" app:value="19")

### CODE REVIEW

**Comment by mathias21** [comment]
Hi @milosmns 

I had to fix a problem with android-maven-gradle-plugin, I hope this is not breaking anything for you. Let me know if you have problems.

Thank you.

**Comment by mathias21** [comment]
Hi @milosmns 

There it is the PR. I hope this will help ;)

Thank you!

**Review by milosmns — APPROVED** [review]
Yep, looks good now.

**Comment by milosmns** [comment]
Considering this fixed.

**Pull request merged**
